### ISSUE TITLE
Caret version range results in breaking changes between versions

### ISSUE THREAD

**Issue by ErisDS** [cibernox/git-repo-version#14]
I wanted to flag up that this repo is depending on version ^1.0.4 of git-repo-info, which means that any version from 1.0.4 to <2.x is permitted to be installed.

Version 1.3.0 of git-repo-info contains a breaking change / bug, see https://github.com/rwjblue/git-repo-info/issues/27. 

This means that any upstream project who uses this module + has a git submodule is now getting errors in their build. We're using a pinned version of ember-cli-app-version which in turn uses a pinned version of git-repo-version, however we're currently unable to run our build without hacking in a force-pinned 1.2.0 version of git-repo-info.

Please consider using a smaller version range, or even a pinned version, in order to prevent these sorts of issues with downstream modules affecting everyone upstream.

Thanks for listening 👋

**Comment by cibernox** [comment]
I can release a version depending on ~1.2.0 until the bug in `git-repo-info` is fixed. Give me a minute.

**Comment by cibernox** [comment]
I've published 0.4.1 that depends on ~1.2.0. I'll keep an eye on that issue and update the dependency once the bug is fixed.

**Comment by ErisDS** [comment]
Thanks 👍
