### ISSUE TITLE
Add the ability to include SHA date to the version

### ISSUE THREAD

**Issue by taras** [cibernox/git-repo-version#16]
`ember-cli-app-version` has an [issue](https://github.com/EmberSherpa/ember-cli-app-version/issues/50) and a [PR](https://github.com/EmberSherpa/ember-cli-app-version/pull/51#pullrequestreview-66370957) to allow displaying SHA date in the version. 

The current PR spawns a system process with a `git` call. It would be better to have `git-repo-version` optionally include the date in the version. 

`git-repo-info` already provides [`authorDate`](https://github.com/rwjblue/git-repo-info#usage) we just need to include it.

Would you accept a PR with this functionality?

**Comment by ondrejsevcik** [comment]
ping @cibernox

**Comment by cibernox** [comment]
I don't oppose to that. If you make it backwards compatible and add a note in the readme I'll merge it.
